<?php
/**
 * @var $_product	Mage_Catalog_Model_Product
 */
?>
<?php
	$_product = $this->getProduct();
	$_helper = $this->helper('catalog/output');
	$helpZoom = $this->helper('infortis_cloudzoom');
	$helpImg = $this->helper('infortis/image');

	//Get image sizes. If height is not specified, aspect ratio will be kept.
    $imgWidth		= intval($helpZoom->getCfg('images/main_width'));
	$imgHeight		= intval($helpZoom->getCfg('images/main_height'));
	$bigImageWidth  = intval($helpZoom->getCfg('general/big_image_width'));
	$bigImageHeight = intval($helpZoom->getCfg('general/big_image_height'));
	
	//If main image width is not specified, use default values
    if ($imgWidth <= 0)
	{
		$imgWidth = 364;
		$imgHeight = 364;
	}
	//$imgBorder = 1;
	//$imgPadd = 5;
	//$imgTotalPadd = ($imgBorder + $imgPadd) * 2; //12
	//$imgWidth -= $imgTotalPadd;
	//$imgHeight -= $imgTotalPadd;
	
	//If main image width is not specified, use default values
    if ($bigImageWidth <= 0)
	{
		$bigImageWidth = 650;
		$bigImageHeight= 650;
	}
	
	//Thumbnail images size
	$thumbImgWidth = 65;
	$thumbImgHeight = 65;
	$thumbTotalPadd = 14; //Additional padding, border and margin (horizontal axis) around the image
	$thumbTotalWidth = $thumbImgWidth + $thumbTotalPadd;
//	$thumbsShowCount = 3;
//	$thumbTotalWidth = floor(($imgWidth * 0.8) / $thumbsShowCount);
//	$thumbImgWidth = $thumbTotalWidth - $thumbTotalPadd;
//	$thumbImgHeight = $thumbTotalWidth - $thumbTotalPadd;

	//Aspect ratio settings
	if ($helpZoom->getCfg('images/aspect_ratio'))
	{
		//Height will be computed automatically (based on width) to keep the aspect ratio of the image
		$imgHeight = 0;
		$bigImageHeight= 0;
		$thumbImgHeight = 0;
	}
?>



<?php //Main image ?>

<div class="img-box img-box-style1">
<?php if ($_product->getImage() != 'no_selection' && $_product->getImage()): ?>

	<?php if($helpZoom->isCloudZoomEnabled()): //If module enabled ?>
    
    	<?php
			$zoomClasses = '';
			if ($helpZoom->useCloudZoom() == false)
				$zoomClasses .= ' simple-mode';
			else
			{
				if ($helpZoom->isPositionInside())
					$zoomClasses .= ' zoom-inside';
			}
		?>
        
        <p class="product-image<?php echo $zoomClasses; ?>">
        
            <a href="<?php echo $helpImg->getImg($_product, $bigImageWidth, $bigImageHeight); ?>" class="cloud-zoom" id="zoom1" rel="<?php echo $helpZoom->getCloudZoomOptions(); ?>">
                <img src="<?php echo $helpImg->getImg($_product, $imgWidth, $imgHeight); ?>" alt="<?php echo $this->escapeHtml($this->getImageLabel());?>" title="<?php echo $this->escapeHtml($this->getImageLabel());?>" />
            </a>
            
            <?php if($helpZoom->useLightbox()): ?>
                <?php
                    $zoomBtnClasses = '';
                    if ($helpZoom->useCloudZoom() == false)
                        $zoomBtnClasses .= ' zoom-btn-large';
                    else
                        $zoomBtnClasses .= ' zoom-btn-small';
                ?>
                <a id="zoom-btn" class="lightbox-group<?php echo $zoomBtnClasses; ?>" href="<?php echo $helpImg->getImg($_product, $bigImageWidth, $bigImageHeight); ?>" title="<?php echo $this->getImageLabel(); ?>"><?php echo $this->__('Zoom'); ?></a>
                
            <?php endif; ?>
        </p>
    
    <?php else: //Module disabled. Show images in Magento default style ?>
    
        <p class="product-image">
        	<img src="<?php echo $helpImg->getImg($_product, $imgWidth, $imgHeight); ?>" alt="<?php echo $this->escapeHtml($this->getImageLabel());?>" title="<?php echo $this->escapeHtml($this->getImageLabel());?>" />
        </p>
    
    <?php endif; ?>
    
<?php else: //No image ?>

    <p class="product-image">
		<?php
        	$_img = '<img src="'.$this->helper('catalog/image')->init($_product, 'image')->resize($imgWidth).'" alt="'.$this->escapeHtml($this->getImageLabel()).'" title="'.$this->escapeHtml($this->getImageLabel()).'" />';
        	echo $_helper->productAttribute($_product, $_img, 'image');
        ?>
    </p>

<?php endif; ?>



<?php //Thumbnails ?>
    
    <?php
        $imageCount = count($this->getGalleryImages());
        
        //Modify thumbnail slider depending on number of thumbnails
		$sliderClasses = '';
		if ($imageCount > 0)
		{
			if ($imageCount <= 5)
				$sliderClasses .= " count-$imageCount";
			else
				$sliderClasses .= " count-multi";
		}
		if ($imageCount < 4)
			$sliderClasses .= ' hide-direction-nav';
    ?>

	<?php if ($imageCount > 0): ?>
    <div class="more-images itemslider itemslider-thumbnails gen-slider-arrows3 <?php if($sliderClasses) echo $sliderClasses; ?>">
        <ul class="thumbnails slides">
        
        <?php //Display thumbnails with cloud zoom or lightbox ?>
        <?php if ($helpZoom->isCloudZoomEnabled()): ?>
        
            <?php foreach ($this->getGalleryImages() as $_image): ?>
                <?php //Skip, if no image
                    if ($_image->getFile() == NULL)
                        continue; ?>
                <li>
                    <a href="<?php echo $helpImg->getImg($_product, $bigImageWidth, $bigImageHeight, 'image', $_image->getFile()); ?>" class="cloud-zoom-gallery lightbox-group" title="<?php echo $this->escapeHtml($_image->getLabel()); ?>"
                        rel="useZoom:'zoom1', smallImage: '<?php echo $helpImg->getImg($_product, $imgWidth, $imgHeight, 'image', $_image->getFile()); ?>'">
                        
                        <img src="<?php echo $helpImg->getImg($_product, $thumbImgWidth, $thumbImgHeight, 'thumbnail', $_image->getFile()); ?>" alt="<?php echo $this->escapeHtml($_image->getLabel()); ?>"/>
                        
                    </a>
                </li>
            <?php endforeach; ?>
        
        <?php else: //Show thumbnails in Magento default style, without cloud zoom and lightbox ?>
        
            <?php foreach ($this->getGalleryImages() as $_image): ?>
                <?php //Skip, if no image
                    if ($_image->getFile() == NULL)
                        continue; ?>
                <li>
                    <a href="#" onclick="popWin('<?php echo $this->getGalleryUrl($_image) ?>', 'gallery', 'width=300,height=300,left=0,top=0,location=no,status=yes,scrollbars=yes,resizable=yes'); return false;" title="<?php echo $this->escapeHtml($_image->getLabel()) ?>">
                        <img src="<?php echo $helpImg->getImg($_product, $thumbImgWidth, $thumbImgHeight, 'thumbnail', $_image->getFile()); ?>" alt="<?php echo $this->escapeHtml($_image->getLabel()) ?>"/>
                    </a>
                </li>
            <?php endforeach; ?>
        
        <?php endif; ?>
        </ul>
    </div> <!-- end: more-images -->
    <?php endif; ?>

</div> <!-- end: img-box -->



<?php echo $this->getChildHtml('lightboxConfig'); ?>

<script type="text/javascript">
//<![CDATA[

	jQuery(function($) {
		var t; $(window).resize(function() { clearTimeout(t); t = setTimeout(function() { $(".more-images .cloud-zoom-gallery").first().click(); }, 200); });
	});

	jQuery(function($) {
		$('.itemslider-thumbnails').flexslider({
			namespace: "",
			animation: "slide",
			easing: "easeInQuart",
			animationSpeed: 300,
			animationLoop: false,
			slideshow: false,
			
			pauseOnHover: true,
			controlNav: false,
			
			itemWidth: <?php echo $thumbTotalWidth; ?>,
			move: 1
		});
	});
//]]>
</script>
